### ISSUE TITLE
Ringer not sounding.

### ISSUE THREAD

**Issue by johngrant** [matchu/Strict-Workflow#53]
Occasionally it seems like the ringer is not sounding at the end of a work session. I'm not sure how to reproduce this. I'm often working in a windows remote desktop session on my main monitor and run the Strict Workflow in a chrome instance on my secondary display. I also have the Spotify Windows app running on my local work station. I don't always hear the buzzer at the end of a work session or it isn't always triggered. I cannot consistently reproduce this yet.

**Comment by matchu** [comment]
Hm. Without reproducing it, I dunno what to tell ya. Lemme know if you
figure something out :/

Maybe when the buzzer is missing, try navigating to the browser's
Extensions page, turning on Developer Mode, and opening up the console for
Strict Workflow. Any red error messages?
