### ISSUE TITLE
No longer blocking existing tabs when timer starts.

### ISSUE THREAD

**Issue by darthschmoo** [matchu/Strict-Workflow#55]
I don't know if it was a Chrome update or an update to the extension.  But now when I click on the tomato, it doesn't block the existing tabs.  New tabs for blocked sites get blocked, but in order to block existing tabs, you have to reload them.

Follow-up: When the timer is turned off, the blocking overlays aren't immediately removed from the page. You have to reload the page to get rid of it.

Follow-follow-up:  I'm on the most up-to-date version of Chrome, and I tried uninstalling and reinstalling the extension.

**Comment by darthschmoo** [comment]
Follow-up: When the timer is turned off, the blocking overlays aren't immediately removed from the page.  You have to reload the page to get rid of it.

**Comment by matchu** [comment]
Hmm, still works for me. Are there any particular sites where it breaks? Is
it maybe conflicting with another extension?

**Comment by darthschmoo** [comment]
Well, it's sixteen months late, but I'm reporting back.  I'm still using The Tomato, and I don't seem to be running into this issue anymore.  Whatever you did, keep it up!
